trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# -------------------
# UAT Deployment
# -------------------
- stage: UAT
  displayName: Deploy UAT

  jobs:
  - job: Deploy_UAT

    steps:

    - checkout: self

    - script: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y terraform
        terraform version
      displayName: Install Terraform

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-service-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show

    - script: |
        cd env/uat
        terraform init
        terraform validate
        terraform plan
        terraform apply -auto-approve
      displayName: Deploy UAT

# -------------------
# PROD Deployment
# -------------------
- stage: PROD
  dependsOn: UAT
  displayName: Deploy PROD

  jobs:
  - job: Deploy_PROD

    steps:

    - checkout: self

    - script: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y terraform
        terraform version
      displayName: Install Terraform

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-service-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az account show

    - script: |
        cd env/prod
        terraform init
        terraform validate
        terraform plan
        terraform apply -auto-approve
      displayName: Deploy PROD
